kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: mysql-master
spec:
  serviceName: mysql-master
  replicas: 1
  selector:
    matchLabels:
      mysql: mysql-master
  template:
    metadata:
      labels:
        mysql: mysql-master
    spec:
      containers:
      - name: mysql-master
        image: 10.112.101.90/cloudzone/mysql-master:5.7
        #image: jcpt/mysql-master-test:5.7
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql-master
        env:
        - name: MYSQL_ROOT_USER
          value: "jcpt"
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_REPLICATION_USER
          value: "repl"
        - name: MYSQL_REPLICATION_PASSWORD
          value: "12345678"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: cephfs-db-pvc
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: mysql-master
  name: mysql-master
spec:
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 8507
  type: NodePort
  selector:
    mysql: mysql-master
